// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart


Future<void> initializeFirebase() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcDgroNcy7fMqHw45M_Y8_zdtRrc3D3tI',
    appId: '1:908186922366:web:df9b5a626eb0d0f962d72f',
    messagingSenderId: '908186922366',
    projectId: 'fish-track-6e054',
    authDomain: 'fish-track-6e054.firebaseapp.com',
    storageBucket: 'fish-track-6e054.appspot.com',
    measurementId: 'G-S56P41F9FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_hKIJWQWfQyCtIVTr2Qig0D5RTWUoh5A',
    appId: '1:908186922366:android:e61cdaf18749a39662d72f',
    messagingSenderId: '908186922366',
    projectId: 'fish-track-6e054',
    storageBucket: 'fish-track-6e054.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuejC-qzhWBPlhVX7O-GdwqLLoMhAVIrk',
    appId: '1:908186922366:ios:66b6f313559b34a262d72f',
    messagingSenderId: '908186922366',
    projectId: 'fish-track-6e054',
    storageBucket: 'fish-track-6e054.appspot.com',
    iosBundleId: 'com.example.fishTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuejC-qzhWBPlhVX7O-GdwqLLoMhAVIrk',
    appId: '1:908186922366:ios:8dc1a64dad94d59162d72f',
    messagingSenderId: '908186922366',
    projectId: 'fish-track-6e054',
    storageBucket: 'fish-track-6e054.appspot.com',
    iosBundleId: 'com.example.fishTrack.RunnerTests',
  );
}


